*.default=true
*.normal=true

default.fg=#cdd6f4

error.fg=#f38ba8
warning.fg=#f9e2af
success.fg=#a6e3a1

tab.fg=#a6adc8
tab.bg=#181825
tab.selected.fg=#cdd6f4
tab.selected.bg=#313244
tab.selected.bold=true

border.fg=#585b70
border.bold=true

msglist_unread.bold=true
msglist_flagged.fg=#f9e2af
msglist_flagged.bold=true
msglist_result.fg=#89b4fa
msglist_result.bold=true
msglist_*.selected.bold=true
msglist_*.selected.bg=#313244
msglist_*.selected.fg=#cdd6f4
msglist_deleted.fg=#6c7086

dirlist_*.selected.bold=true
dirlist_*.selected.bg=#313244
dirlist_*.selected.fg=#cdd6f4

statusline_default.fg=#a6adc8
statusline_default.bg=#313244
statusline_error.fg=#f38ba8
statusline_error.bold=true
statusline_success.bold=true

completion_default.selected.bg=#313244
completion_description.dim=true

part_filename.selected.fg=#cdd6f4
part_filename.selected.bg=#313244
part_switcher.selected.bg=#313244

part_mimetype.selected.fg=#cdd6f4
part_mimetype.selected.bg=#313244

selector_focused.bold=true
selector_focused.bg=#313244
selector_focused.fg=#cdd6f4

[viewer]
url.fg=#89b4fa
url.underline=true
header.bold=true
signature.dim=true
diff_meta.bold=true
diff_chunk.fg=#89b4fa
diff_chunk_func.fg=#89b4fa
diff_chunk_func.bold=true
diff_add.fg=#a6e3a1
diff_del.fg=#f38ba8
quote_1.fg=#89b4fa
quote_2.fg=#fab387
quote_3.fg=#b4befe
quote_4.fg=#f5c2e7
quote_x.fg=#6c7086

