[audio]
enable_sounds = true

[backdrop]
enabled = true

[bar.default]
auto_hide = false
background_opacity = 0.099999997764825821
capsule_group = []
center = [ "clock", "cat", "media" ]
concave_edge_corners = true
end = [ "tray", "notifications", "network", "volume", "battery" ]
font_weight = 400
layer = "top"
margin_ends = 192
padding = 16
position = "bottom"
radius = 16
reserve_space = true
shadow = false
show_on_workspace_switch = false
start = [ "workspaces" ]
thickness = 32
widget_spacing = 10

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 5

[calendar]
enabled = true

    [calendar.account.houseplants_cal]
    calendars = [
        "personal",
        "02B695BE-0A2A-49F7-9123-57102E1B9213",
        "routines",
        "316EC6A0-39CC-4207-BF20-F5AAFF41919E",
        "love-computer",
        "96E8D86B-8B89-4819-93A8-A766D22E99C1",
        "018ED70D-2567-4A5F-919B-76FCD0328BD1",
        "contact_birthdays"
    ]
    credential_source = "file"
    name = "Houseplants"
    password_file = "/run/secrets/ivy-nextcloud-app-password"
    provider = "custom"
    server_url = "https://nc.houseplants.cloud/remote.php/dav"
    type = "caldav"
    username = "ivy"

[control_center]
hidden_tabs = [ "audio", "monitor", "screen-time" ]
show_session_button = false
show_shortcut_labels = false
sidebar_section = "none"
width = 620

    [control_center.calendar]
    show_week_numbers = true

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "weather"

[desktop_widgets]
enabled = false

[dock]
auto_hide = true
background_opacity = 0.4999999888241291
concave_edge_corners = false
margin_edge = 16
reserve_space = false
show_dots = true

[hot_corners]
enabled = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 15

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 400.0

[location]
auto_locate = true

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0001220703125
    cy = 1018.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true

[notification]
filter_order = [ "filter" ]
history_retention_hours = 1

    [notification.filter.filter]
    allow_permanent = false
    enabled = true
    match = "claude"
    play_sound = true
    save_history = false
    show_toast = true

[osd]
background_opacity = 0.4999999888241291
border = false
position_vertical = "top_right"

    [osd.kinds]
    lock_keys = false
    privacy = false

[plugins]
enabled = [ "noctalia/bongocat", "nightwatch75/file-search", "noctalia/wallhaven", "lowcache/claude-companion" ]

[shell]
app_icon_color = "primary"
app_icon_colorize = true
external_ip_enabled = true
font_family = "Aporetic Sans"
launch_apps_as_systemd_services = true
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
popup_shadows = false
screen_time_enabled = true
settings_show_advanced = false
settings_window_translucent = true
show_location = false
telemetry_enabled = true

    [shell.launcher]
    categories = false
    compact = true
    pinned = [ "firefox", "emacs", "vesktop", "feishin" ]
    show_app_origin_indicator = false
    show_icons = false
    sort_by_usage = false

    [shell.mpris]
    blacklist = [ "firefox" ]

    [shell.panel]
    clipboard_position = "center_right"
    control_center_placement = "floating"
    launcher_placement = "attached"
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    shadow = true
    transparency_mode = "soft"
    wallpaper_placement = "floating"

    [shell.screenshot]
    directory = "/home/ivy/media/screenshots"
    pipe_command = "swappy -f -"
    pipe_to_command = true

    [shell.session]
    grid = true
    show_shortcuts = false

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = true
        label = "logout"
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        label = "reboot"
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        label = "shutdown"
        shortcut = "3"
        variant = "destructive"

[theme]
builtin = "Ayu"
community_palette = "Catppuccin Mocha Sapphire"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    builtin_ids = [ "btop", "emacs", "gtk3", "gtk4", "ghostty", "kcolorscheme", "niri", "qt" ]
    community_ids = [
        "opencode",
        "pi-agent",
        "feishin",
        "pywalfox-beta4",
        "discord",
        "nchat",
        "senpai",
        "obsidian",
        "zathura",
        "bat",
        "lazygit",
        "yazi"
    ]

        [theme.templates.user.aerc]
        input_path = "$XDG_CONFIG_HOME/noctalia/templates/aerc.conf"
        output_path = "$XDG_CONFIG_HOME/aerc/stylesets/noctalia"

        [theme.templates.user.fzf]
        input_path = "$XDG_CONFIG_HOME/noctalia/templates/fzf.sh"
        output_path = "$XDG_CONFIG_HOME/fzf/noctalia-colors.sh"

        [theme.templates.user.tmux]
        input_path = "$XDG_CONFIG_HOME/noctalia/templates/tmux.conf"
        output_path = "$XDG_CONFIG_HOME/tmux/noctalia-theme.conf"

        [theme.templates.user.neovim]
        input_path = "$XDG_CONFIG_HOME/noctalia/templates/nvim-matugen.lua"
        output_path = "$XDG_CONFIG_HOME/nvim-noctalia/matugen.lua"
        post_hook = "pkill -SIGUSR1 nvim || true"

[wallpaper]
directory = "/home/ivy/media/images/wallpapers"
transition_on_startup = true

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/ivy/media/images/wallpapers/bafkreia6j6rjttfeem6wf3mbwgeaxbynef2ikgl2mjxozdennuzioq6i2m.webp"

    [wallpaper.last]
    path = "/home/ivy/media/images/wallpapers/bafkreia6j6rjttfeem6wf3mbwgeaxbynef2ikgl2mjxozdennuzioq6i2m.webp"

    [wallpaper.monitors.eDP-1]
    path = "/home/ivy/media/images/wallpapers/bafkreia6j6rjttfeem6wf3mbwgeaxbynef2ikgl2mjxozdennuzioq6i2m.webp"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/ivy/media/images/wallpapers/wallhaven-5gwvz5.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/ivy/media/images/wallpapers/wallhaven-e76pew.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-fruit-salad"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/ivy/media/images/wallpapers/painting-lighthouse-02-1440p.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-fruit-salad"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/ivy/media/images/wallpapers/wallhaven_4dolyl.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/ivy/media/images/wallpapers/oc_the_blackboard.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

[widget.active_window]
display = "text_only"
max_length = 500
min_length = 0

[widget.battery]
hide_when_full = true

[widget.cat]
audio_spectrum = true
scale = 1.1000000000000001
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.media]
hide_when_no_media = true
max_length = 500

[widget.network]
show_label = false
show_vpn_label = true
vpn_status = "both"

[widget.notifications]
hide_when_no_unread = true

[widget.tray]
drawer = true

[widget.workspaces]
hide_when_empty = true
show_labels = false
